version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: connect_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    networks:
      - connect_test

networks:
  connect_test:
    driver: bridge
